### ISSUE TITLE
Error messages in Examples\Econometrics\DSGE\Gabaix\JPR\run_jpr.m

### ISSUE THREAD

**Issue by taaursland** [Coksp1/NBTOOLBOX#2]
The example does not run uninterrupted. 

- Error message on line 48 (solving the linear Gabaix model): "Invertibility condition violated. Blanchard-Kahn rank condition not satisfied.". 
- Error message on line 124 (solving the non-linear model with Gabaix discounting in all equations): "setDiscount:: The discount factor applied to all equation cannot be found to be a parameter;"

**Comment by Coksp1** [comment]
This should have bee fixed. Thanks for noticing me of this issue.
